// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet_client.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	packet_client.proto

It has these top-level messages:
	PK_LOGIN
	PK_LOGIN_R
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PK_LOGINCmd int32

const (
	PK_LOGIN_begin PK_LOGINCmd = 0
	PK_LOGIN_CMD   PK_LOGINCmd = 168493057
)

var PK_LOGINCmd_name = map[int32]string{
	0:         "begin",
	168493057: "CMD",
}
var PK_LOGINCmd_value = map[string]int32{
	"begin": 0,
	"CMD":   168493057,
}

func (x PK_LOGINCmd) String() string {
	return proto.EnumName(PK_LOGINCmd_name, int32(x))
}
func (PK_LOGINCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type PK_LOGIN_RCmd int32

const (
	PK_LOGIN_R_begin PK_LOGIN_RCmd = 0
	PK_LOGIN_R_CMD   PK_LOGIN_RCmd = 185204737
)

var PK_LOGIN_RCmd_name = map[int32]string{
	0:         "begin",
	185204737: "CMD",
}
var PK_LOGIN_RCmd_value = map[string]int32{
	"begin": 0,
	"CMD":   185204737,
}

func (x PK_LOGIN_RCmd) String() string {
	return proto.EnumName(PK_LOGIN_RCmd_name, int32(x))
}
func (PK_LOGIN_RCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type PK_LOGIN struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *PK_LOGIN) Reset()                    { *m = PK_LOGIN{} }
func (m *PK_LOGIN) String() string            { return proto.CompactTextString(m) }
func (*PK_LOGIN) ProtoMessage()               {}
func (*PK_LOGIN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PK_LOGIN) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PK_LOGIN_R struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *PK_LOGIN_R) Reset()                    { *m = PK_LOGIN_R{} }
func (m *PK_LOGIN_R) String() string            { return proto.CompactTextString(m) }
func (*PK_LOGIN_R) ProtoMessage()               {}
func (*PK_LOGIN_R) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PK_LOGIN_R) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*PK_LOGIN)(nil), "pb.PK_LOGIN")
	proto.RegisterType((*PK_LOGIN_R)(nil), "pb.PK_LOGIN_R")
	proto.RegisterEnum("pb.PK_LOGINCmd", PK_LOGINCmd_name, PK_LOGINCmd_value)
	proto.RegisterEnum("pb.PK_LOGIN_RCmd", PK_LOGIN_RCmd_name, PK_LOGIN_RCmd_value)
}

func init() { proto.RegisterFile("packet_client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0x89, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2a, 0x48, 0x52, 0xb2, 0xe1, 0xe2, 0x08, 0xf0, 0x8e, 0xf7, 0xf1, 0x77, 0xf7, 0xf4, 0x13,
	0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3,
	0x95, 0x64, 0xb8, 0x98, 0x93, 0x73, 0x53, 0x84, 0x38, 0xb9, 0x58, 0x93, 0x52, 0xd3, 0x33, 0xf3,
	0x04, 0x18, 0x84, 0xb8, 0xb8, 0x98, 0x9d, 0x7d, 0x5d, 0x04, 0x1a, 0x1b, 0xd6, 0x04, 0x28, 0xd9,
	0x71, 0x71, 0xc1, 0x74, 0xc7, 0x07, 0x81, 0xf4, 0x27, 0xe7, 0xa7, 0x40, 0xf4, 0xb3, 0x06, 0x81,
	0xd9, 0xf8, 0xf4, 0xaf, 0x88, 0x48, 0x62, 0x03, 0x3b, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xaf, 0x4f, 0xa3, 0x7b, 0x9f, 0x00, 0x00, 0x00,
}
